### PR TITLE
 Circumvented App Engine file write issue with comparing lists instead 

### PR DESCRIPTION
**Pull request by Ayaykos**

### CODE REVIEW

**Comment by jonespm** [comment]
Cool this looks like it will work, did you try
`deepdiff[murmur]`

in the requirements? It says "Otherwise DeepDiff will be using SHA256 for hashing which is a cryptographic hash and is considerably slower."

**Comment by jonespm** [comment]
Also looks like the popular numpy has setdiff1d

https://docs.scipy.org/doc/numpy-1.13.0/reference/generated/numpy.setdiff1d.html

**Comment by Ayaykos** [comment]
Thanks for the heads up about murmur, didn't catch that.
Setdiff1d doesn't give enough information as it only compares one list's unique values that the other doesn't have, not also the other way around (so only additions or deletions but not both).

**Review by jonespm — APPROVED** [review]

**Comment by Ayaykos** [comment]
So the requirements folder still needs deepdiff==4.0.6, it just also needs mmh3==2.5.1 which is what `pip install deepdiff[murmur]` installs additionally.

**Comment by jonespm** [comment]
Great, I didn't know how that worked in the requirements file, thanks for checking.

**Pull request merged**
